 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codecrew.view;


/**
 *
 * @author USER
 */

import com.codecrew.admin.auth.Auth;
import com.codecrew.LecturerSession;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userIdBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passwordBox = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        backgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 90, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("User Id");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 100, 40));

        userIdBox.setBackground(new java.awt.Color(255, 255, 255));
        userIdBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userIdBox.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(userIdBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 260, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Password");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 100, 40));

        passwordBox.setBackground(new java.awt.Color(255, 255, 255));
        passwordBox.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordBox.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(passwordBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 260, 40));

        loginBtn.setBackground(new java.awt.Color(51, 255, 0));
        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 0, 0));
        loginBtn.setText("Login");
        loginBtn.setOpaque(true);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 110, 40));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/codecrew/view/360_F_566235195_nhDDuQpommcxK9SBtY2gq5IxvsJxCIdE.jpg"))); // NOI18N
        getContentPane().add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String uName = userIdBox.getText();
        String pWord = passwordBox.getText();
        
        ResultSet authenticatedUser;
  
        try {
            authenticatedUser = Auth.getAuth(uName,pWord);
            if(authenticatedUser==null){
                JOptionPane.showMessageDialog(rootPane, "username or password incorrect !");
                return;
            }
            if(authenticatedUser.getString("Role").equals("Student")){
                StudentPannel sp = new StudentPannel(authenticatedUser.getString("U_Id"), authenticatedUser.getString("Uname"), Long.parseLong(authenticatedUser.getString("Contact")) , authenticatedUser.getString("Email"), authenticatedUser.getBytes("image_data"), authenticatedUser.getString("Department"));
                sp.setVisible(true);
                this.dispose();
               
            }else if(authenticatedUser.getString("Role").equals("Technical Officer")){
               
                com.codecrew.ToHome toHome = new com.codecrew.ToHome();
                toHome.setVisible(true);
                this.dispose();
            }else if(authenticatedUser.getString("Role").equals("Lecturer")){
                LecturerSession.setSession(
                    authenticatedUser.getString("U_Id"),
                    authenticatedUser.getString("Uname"),
                    authenticatedUser.getString("Email"),
                    authenticatedUser.getString("Department")
                );
                com.codecrew.LecturerDashboard dash = new com.codecrew.LecturerDashboard(
                    authenticatedUser.getString("U_Id"),
                    authenticatedUser.getString("Uname"),
                    authenticatedUser.getString("Email"),
                    authenticatedUser.getString("Department")
                );
                dash.setVisible(true);
                this.dispose();
            }
            
            else{
                JOptionPane.showMessageDialog(null, "you have not accessed role !");
            }
        } catch (ClassNotFoundException ex) {
            throw new ClassCastException();
        } catch (SQLException ex) {
            try {
                throw new SQLException();
            } catch (SQLException ex1) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField passwordBox;
    private javax.swing.JTextField userIdBox;
    // End of variables declaration//GEN-END:variables
}
