package com.codecrew.view.netbeans;

import com.codecrew.dao.CourseDAO;
import com.codecrew.model.CourseUnit;
import com.codecrew.model.User;
import com.codecrew.util.UIHelper;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
import javax.swing.border.EmptyBorder;

/**
 * CoursesTableForm - NetBeans GUI Builder compatible table form
 * 
 * TO CUSTOMIZE IN NETBEANS:
 * 1. Open this file in NetBeans IDE
 * 2. Open the .form file in GUI Builder
 * 3. Drag and drop components to design
 * 4. Edit properties in Properties window
 * 5. Save - code is auto-generated
 * 
 * @author CodeCrew
 */
public class CoursesTableForm extends javax.swing.JPanel {

    private User currentUser;
    private CourseDAO courseDAO;
    private DefaultTableModel tableModel;

    // Customizable colors
    public static Color FORM_BG = UIHelper.BG;
    public static Color CARD_BG = Color.WHITE;
    public static Color PRIMARY = UIHelper.PRIMARY;

    public CoursesTableForm() {
        courseDAO = new CourseDAO();
        initComponents();
        applyStyles();
    }

    public CoursesTableForm(User user) {
        this.currentUser = user;
        courseDAO = new CourseDAO();
        initComponents();
        applyStyles();
        loadCourses();
    }

    private void applyStyles() {
        setBackground(FORM_BG);
        cardPanel.setBackground(CARD_BG);
        lblTitle.setFont(UIHelper.FONT_TITLE);
        lblTitle.setForeground(PRIMARY);
        
        // Style table
        tblCourses.setFont(UIHelper.FONT_BODY);
        tblCourses.setRowHeight(30);
        tblCourses.setSelectionBackground(new Color(219, 234, 254));
    }

    private void loadCourses() {
        tableModel = (DefaultTableModel) tblCourses.getModel();
        tableModel.setRowCount(0);
        
        if (currentUser != null) {
            List<CourseUnit> courses = courseDAO.getEnrolledCourses(currentUser.getuId());
            for (CourseUnit c : courses) {
                tableModel.addRow(new Object[]{
                    c.getCourseCode(),
                    c.getName(),
                    c.getCredit(),
                    "-"
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();

        setBackground(new java.awt.Color(241, 245, 249));
        setLayout(new java.awt.BorderLayout(0, 16));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(30, 58, 138));
        lblTitle.setText("My Courses");
        add(lblTitle, java.awt.BorderLayout.NORTH);

        cardPanel.setBackground(java.awt.Color.WHITE);
        cardPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)),
            new javax.swing.EmptyBorder(16, 16, 16, 16)));
        cardPanel.setLayout(new java.awt.BorderLayout(0, 10));

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"CS101", "Intro to Programming", 3, "A"},
                {"CS102", "Data Structures", 3, "A-"},
                {"MATH101", "Calculus I", 4, "B+"}
            },
            new String [] {
                "Code", "Name", "Credits", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCourses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCourses.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblCourses);

        cardPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(cardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JPanel cardPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourses;
    // End of variables declaration                   

    // ─── PUBLIC METHODS ─────────────────────────────────────────────────────

    public void refreshData() {
        loadCourses();
    }

    public User getCurrentUser() { return currentUser; }
    public void setCurrentUser(User user) { 
        this.currentUser = user; 
        loadCourses(); 
    }

    public JTable getTable() { return tblCourses; }
    public DefaultTableModel getTableModel() { return tableModel; }

    // ─── MAIN FOR TESTING ───────────────────────────────────────────────────
    public static void main(String[] args) {
        UIHelper.setLookAndFeel();
        JFrame frame = new JFrame("Courses Table Form Test");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(700, 500);
        
        User testUser = new User("ST001", "John", "Doe", "john@edu", 
            "Address", "Male", "2000-01-01", "Student", "Computing");
        frame.add(new CoursesTableForm(testUser));
        
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}