package com.codecrew.view.netbeans;

import com.codecrew.model.User;
import com.codecrew.util.UIHelper;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/**
 * StudentForm - NetBeans GUI Builder compatible form
 * 
 * TO CUSTOMIZE IN NETBEANS:
 * 1. Open this file in NetBeans IDE
 * 2. Open the .form file in GUI Builder
 * 3. Drag and drop components to design
 * 4. Edit properties in Properties window
 * 5. Save - code is auto-generated
 * 
 * @author CodeCrew
 */
public class StudentForm extends javax.swing.JPanel {

    private User currentUser;
    
    // Customizable colors - change in code or NetBeans properties
    public static Color FORM_BG = UIHelper.BG;
    public static Color CARD_BG = Color.WHITE;
    public static Color PRIMARY = UIHelper.PRIMARY;

    public StudentForm() {
        initComponents();
        applyCustomStyles();
    }

    public StudentForm(User user) {
        this.currentUser = user;
        initComponents();
        applyCustomStyles();
        loadData();
    }

    private void applyCustomStyles() {
        setBackground(FORM_BG);
        cardPanel.setBackground(CARD_BG);
        lblTitle.setFont(UIHelper.FONT_TITLE);
        lblTitle.setForeground(PRIMARY);
    }

    private void loadData() {
        if (currentUser != null) {
            lblTitle.setText("Welcome, " + currentUser.getFname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 245, 249));
        setLayout(new java.awt.BorderLayout(0, 16));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(30, 58, 138));
        lblTitle.setText("Student Profile");
        add(lblTitle, java.awt.BorderLayout.NORTH);

        cardPanel.setBackground(java.awt.Color.WHITE);
        cardPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)),
            new javax.swing.EmptyBorder(16, 16, 16, 16)));
        cardPanel.setLayout(new java.awt.GridLayout(0, 2, 20, 12));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 85, 105));
        jLabel1.setText("Student ID");
        cardPanel.add(jLabel1);

        txtStudentId.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtStudentId.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)),
            new javax.swing.EmptyBorder(6, 10, 6, 10)));
        cardPanel.add(txtStudentId);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 85, 105));
        jLabel2.setText("Full Name");
        cardPanel.add(jLabel2);

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtName.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)),
            new javax.swing.EmptyBorder(6, 10, 6, 10)));
        cardPanel.add(txtName);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 85, 105));
        jLabel3.setText("Email");
        cardPanel.add(jLabel3);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 213, 225)),
            new javax.swing.EmptyBorder(6, 10, 6, 10)));
        cardPanel.add(txtEmail);

        jLabel4.setText(" "); // NOI18N
        cardPanel.add(jLabel4);

        javax.swing.JPanel btnPanel = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));
        btnPanel.setOpaque(false);

        btnSave.setBackground(new java.awt.Color(30, 58, 138));
        btnSave.setForeground(java.awt.Color.WHITE);
        btnSave.setText("Save");
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setFocusPainted(false);
        btnSave.setPreferredSize(new java.awt.Dimension(100, 36));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnPanel.add(btnSave);

        btnCancel.setBackground(new java.awt.Color(71, 85, 105));
        btnCancel.setForeground(java.awt.Color.WHITE);
        btnCancel.setText("Cancel");
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancel.setFocusPainted(false);
        btnCancel.setPreferredSize(new java.awt.Dimension(100, 36));
        btnPanel.add(btnCancel);

        cardPanel.add(btnPanel);

        add(cardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // Add your save logic here
        JOptionPane.showMessageDialog(this, "Data saved!", "Success", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration                   

    // ─── GETTER/SETTER METHODS ───────────────────────────────────────────────
    
    public String getStudentId() { return txtStudentId.getText(); }
    public void setStudentId(String id) { txtStudentId.setText(id); }
    
    public String getName() { return txtName.getText(); }
    public void setName(String name) { txtName.setText(name); }
    
    public String getEmail() { return txtEmail.getText(); }
    public void setEmail(String email) { txtEmail.setText(email); }

    public User getCurrentUser() { return currentUser; }
    public void setCurrentUser(User user) { 
        this.currentUser = user; 
        loadData(); 
    }

    // ─── MAIN FOR TESTING ───────────────────────────────────────────────────
    public static void main(String[] args) {
        UIHelper.setLookAndFeel();
        JFrame frame = new JFrame("Student Form Test");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(600, 400);
        
        User testUser = new User("ST001", "John", "Doe", "john@edu", 
            "Address", "Male", "2000-01-01", "Student", "Computing");
        frame.add(new StudentForm(testUser));
        
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}