/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codecrew;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nipun
 */
public class ToAddMedical extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToAddMedical.class.getName());

    /**
     * Creates new form ToAddMedical
     */
    public ToAddMedical() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medicalRecordsShowTable = new javax.swing.JTable();
        addMedicalApproveButton = new javax.swing.JButton();
        addMedicalRejectButton = new javax.swing.JButton();
        addMedicalAddButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sessionResultShowTable = new javax.swing.JTable();
        AddMedicalStudentId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addMedicalReason = new javax.swing.JTextField();
        addMedicalCourseCode = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        addMedicalRequestType = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        addMedicalSearchButton = new javax.swing.JButton();
        medicalRefreshButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 760));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ADD MEDICAL");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Course Code");

        medicalRecordsShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Student ID", "Course Code", "Request Type", "Reason", "Status"
            }
        ));
        jScrollPane1.setViewportView(medicalRecordsShowTable);

        addMedicalApproveButton.setBackground(new java.awt.Color(51, 255, 0));
        addMedicalApproveButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addMedicalApproveButton.setText("Approve");
        addMedicalApproveButton.addActionListener(this::addMedicalApproveButtonActionPerformed);

        addMedicalRejectButton.setBackground(new java.awt.Color(255, 0, 0));
        addMedicalRejectButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addMedicalRejectButton.setForeground(new java.awt.Color(255, 255, 255));
        addMedicalRejectButton.setText("Reject");
        addMedicalRejectButton.addActionListener(this::addMedicalRejectButtonActionPerformed);

        addMedicalAddButton.setBackground(new java.awt.Color(255, 153, 0));
        addMedicalAddButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addMedicalAddButton.setForeground(new java.awt.Color(255, 255, 255));
        addMedicalAddButton.setText("Add ");
        addMedicalAddButton.addActionListener(this::addMedicalAddButtonActionPerformed);

        sessionResultShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ID", "Date", "Session No", "Session_Type"
            }
        ));
        sessionResultShowTable.setToolTipText("date");
        jScrollPane2.setViewportView(sessionResultShowTable);

        AddMedicalStudentId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Reason");

        addMedicalReason.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addMedicalReason.setBorder(null);
        addMedicalReason.addActionListener(this::addMedicalReasonActionPerformed);

        addMedicalCourseCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addMedicalCourseCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT1212", "ICT1222", "ICT1233", "ICT1242", "ICT1253", "ICT2122", "TCS1212", "TMS1213", "TMS1222", "TMS1231", "TMS1233", "TMS1242", "TMS1253", "TMS1261", "ENT1212", "ENG1222", "BST1272", "BST1262", "BST1253", "BST1242", "BST1232", "BST1222", "BST1212" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Request Type");

        addMedicalRequestType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addMedicalRequestType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Attendance", "CA", "Final_Exam", "Quiz" }));
        addMedicalRequestType.setBorder(null);
        addMedicalRequestType.addActionListener(this::addMedicalRequestTypeActionPerformed);

        addMedicalSearchButton.setBackground(new java.awt.Color(255, 153, 0));
        addMedicalSearchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addMedicalSearchButton.setForeground(new java.awt.Color(255, 255, 255));
        addMedicalSearchButton.setText("Search");
        addMedicalSearchButton.setBorder(null);
        addMedicalSearchButton.addActionListener(this::addMedicalSearchButtonActionPerformed);

        medicalRefreshButton.setBackground(new java.awt.Color(153, 255, 153));
        medicalRefreshButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        medicalRefreshButton.setText("Refresh");
        medicalRefreshButton.addActionListener(this::medicalRefreshButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddMedicalStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addMedicalCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(358, 358, 358)
                                .addComponent(addMedicalSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(169, 169, 169))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addMedicalApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(addMedicalRejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medicalRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(addMedicalAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(203, 203, 203)
                                .addComponent(addMedicalRequestType, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addMedicalReason, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(addMedicalCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddMedicalStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addMedicalSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMedicalReason)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMedicalRequestType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addMedicalAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(medicalRefreshButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMedicalApproveButton)
                    .addComponent(addMedicalRejectButton))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMedicalRequestTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalRequestTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicalRequestTypeActionPerformed

    private void addMedicalAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalAddButtonActionPerformed
        
            int row = sessionResultShowTable.getSelectedRow();

            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Select a session first!");
                return;
            }
            
            
            String studentId = AddMedicalStudentId.getText();
            String courseCode = addMedicalCourseCode.getSelectedItem().toString();
            String reason = addMedicalReason.getText();
            String requestType = addMedicalRequestType.getSelectedItem().toString();

            if (studentId.isEmpty() || reason.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Fill all fields!");
                return;
            }
            
            int sessionId = (int) sessionResultShowTable.getValueAt(row, 0);

            String sql = "INSERT INTO tomedical_record (ST_Id, Course_code, Session_Id, Request_Type, Date_Submit, Reason, Status) VALUES (?, ?, ?, ?, CURDATE(), ?, 'Pending')";
            
            try (Connection con = ToConnect.getConnection();
               PreparedStatement pst = con.prepareStatement(sql)) {

               pst.setString(1, studentId);
               pst.setString(2, courseCode);
               pst.setInt(3, sessionId);
               pst.setString(4, requestType);
               pst.setString(5, reason);

               pst.executeUpdate();

               JOptionPane.showMessageDialog(this, "Medical added!");

               loadPending(); // refresh bottom table

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicalAddButtonActionPerformed

    private void addMedicalSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalSearchButtonActionPerformed
         
            String courseCode = addMedicalCourseCode.getSelectedItem().toString();
            String studentId = AddMedicalStudentId.getText();
            
            String sql = "SELECT s.Session_Id, s.Session_Date, s.Session_Number, s.Session_Type FROM session s WHERE s.Course_code = ? AND NOT EXISTS (    SELECT 1 FROM tomedical_record m   WHERE m.Session_Id = s.Session_Id AND m.ST_Id = ? )";
            
            try (Connection con = ToConnect.getConnection();
                PreparedStatement pst = con.prepareStatement(sql)) {

               pst.setString(1, courseCode);
               pst.setString(2, studentId);

               ResultSet rs = pst.executeQuery();

               DefaultTableModel model = (DefaultTableModel) sessionResultShowTable.getModel();
               model.setRowCount(0);

               while (rs.next()) {
                   model.addRow(new Object[]{
                       rs.getInt("Session_Id"),
                       rs.getDate("Session_Date"),
                       rs.getInt("Session_Number"),
                       rs.getString("Session_Type")
                   });
            }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
// TODO add your handling code here:
    }//GEN-LAST:event_addMedicalSearchButtonActionPerformed

    private void addMedicalApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalApproveButtonActionPerformed


            int row = medicalRecordsShowTable.getSelectedRow();

            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Select a record!");
                return;
            }

            int recordId = (int) medicalRecordsShowTable.getValueAt(row, 0);

            String updateMedical = "UPDATE tomedical_record SET Status='Approved', Approved_By='Chathura Fernando', Approved_Date=CURDATE() WHERE Record_Id=?";

            String getData = "SELECT ST_Id, Session_Id FROM tomedical_record WHERE Record_Id=?";
            String updateAttendance = "UPDATE toattendance SET Status='Medical' WHERE ST_Id=? AND Session_Id=?";

            Connection con = null;

            try {
                con = ToConnect.getConnection();
                con.setAutoCommit(false);

                // 1. Get student + session
                PreparedStatement pst1 = con.prepareStatement(getData);
                pst1.setInt(1, recordId);
                ResultSet rs = pst1.executeQuery();

                String stId = null;
                int sessionId = 0;

                if (rs.next()) {
                    stId = rs.getString("ST_Id");
                    sessionId = rs.getInt("Session_Id");
                }

                // 2. Update medical record
                PreparedStatement pst2 = con.prepareStatement(updateMedical);
                pst2.setInt(1, recordId);
                pst2.executeUpdate();

                // 3. Update attendance
                PreparedStatement pst3 = con.prepareStatement(updateAttendance);
                pst3.setString(1, stId);
                pst3.setInt(2, sessionId);
                pst3.executeUpdate();

                con.commit();

                JOptionPane.showMessageDialog(this, "Approved & Attendance Updated!");

                loadPending();

            } catch (Exception e) {
                try {
                    if (con != null) con.rollback();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

                JOptionPane.showMessageDialog(this, e.getMessage());

            } finally {
                try {
                    if (con != null) con.setAutoCommit(true);
                    if (con != null) con.close();
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicalApproveButtonActionPerformed

    private void addMedicalRejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalRejectButtonActionPerformed

         int row = medicalRecordsShowTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a record!");
            return;
        }

        int recordId = (int) medicalRecordsShowTable.getValueAt(row, 0);

        String sql = "UPDATE tomedical_record SET " +
                     "Status='Rejected', " +
                     "Approved_By='Chathura Fernando', " +
                     "Approved_Date=CURDATE() " +
                     "WHERE Record_Id=?";

        try (Connection con = ToConnect.getConnection();
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setInt(1, recordId);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Rejected!");

            loadPending();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicalRejectButtonActionPerformed

    private void medicalRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalRefreshButtonActionPerformed
        
        loadPending();
        JOptionPane.showMessageDialog(this, "Table refreshed!");
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalRefreshButtonActionPerformed

    private void addMedicalReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedicalReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMedicalReasonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToAddMedical().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddMedicalStudentId;
    private javax.swing.JButton addMedicalAddButton;
    private javax.swing.JButton addMedicalApproveButton;
    private javax.swing.JComboBox<String> addMedicalCourseCode;
    private javax.swing.JTextField addMedicalReason;
    private javax.swing.JButton addMedicalRejectButton;
    private javax.swing.JComboBox<String> addMedicalRequestType;
    private javax.swing.JButton addMedicalSearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable medicalRecordsShowTable;
    private javax.swing.JButton medicalRefreshButton;
    private javax.swing.JTable sessionResultShowTable;
    // End of variables declaration//GEN-END:variables

    private void loadPending() {
        
        String sql = "SELECT Record_Id, ST_Id, Course_code, Request_Type, Reason, Status FROM tomedical_record WHERE Status = 'Pending'";

        try (Connection con = ToConnect.getConnection();
             PreparedStatement pst = con.prepareStatement(sql);
             ResultSet rs = pst.executeQuery()) {

            DefaultTableModel model = (DefaultTableModel) medicalRecordsShowTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("Record_Id"),
                    rs.getString("ST_Id"),
                    rs.getString("Course_code"),
                    rs.getString("Request_Type"),
                    rs.getString("Reason"),
                    rs.getString("Status")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}
