/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codecrew;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author nipun
 */
public class ToAddAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToAddAttendance.class.getName());

    /**
     * Creates new form ToAddAttendance
     */
    public ToAddAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AttendanceStudentId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AttendanceCourseCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AttendanceWeekNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AttendanceSessionNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AttendanceSessionDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AttendanceSessionType = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        AttendanceStatus = new javax.swing.JTextField();
        AttendanceAddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ADD ATTENDANCE");

        jLabel2.setText("Student ID");

        jLabel4.setText("Course Code");

        jLabel3.setText("Week No");

        jLabel6.setText("Session No");

        jLabel5.setText("Session Date");

        jLabel8.setText("Session Type");

        jLabel7.setText("Status");

        AttendanceAddButton.setText("ADD");
        AttendanceAddButton.addActionListener(this::AttendanceAddButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AttendanceStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendanceCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendanceWeekNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendanceSessionNo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendanceSessionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AttendanceSessionType, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(AttendanceAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceWeekNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceSessionNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceSessionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceSessionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(AttendanceAddButton)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttendanceAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceAddButtonActionPerformed

         if(AttendanceStudentId.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceStudentId.requestFocus();
         }
         else if(AttendanceCourseCode.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceCourseCode.requestFocus();
         }
         else if(AttendanceWeekNo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceWeekNo.requestFocus();
         }
         else if(AttendanceSessionNo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceSessionNo.requestFocus();
         }
         else if(AttendanceSessionDate.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceSessionDate.requestFocus();
         }
         else if(AttendanceSessionType.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceSessionType.requestFocus();
         }
         else if(AttendanceStatus.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceStatus.requestFocus();
         }
         else{
             
             try {
                    Connection con = ToConnect.getConnection();
                    
                    PreparedStatement checkSession = con.prepareStatement(
                        "SELECT Session_Id FROM session WHERE Course_code=? AND Week_Number=? AND Session_Number=? AND Session_Date=? AND Session_Type=?"
                    );

                    checkSession.setString(1, AttendanceCourseCode.getText());
                    checkSession.setInt(2, Integer.parseInt(AttendanceWeekNo.getText()));
                    checkSession.setInt(3, Integer.parseInt(AttendanceSessionNo.getText()));
                    checkSession.setString(4, AttendanceSessionDate.getText());
                    checkSession.setString(5, AttendanceSessionType.getText());

                    ResultSet rs = checkSession.executeQuery();

                    int sessionId = 0;

                    if (rs.next()) {
                        // Session already exists
                        sessionId = rs.getInt("Session_Id");
                    } else {
                        // Insert new session
                        PreparedStatement pst = con.prepareStatement(
                            "INSERT INTO session (Course_code, Week_Number, Session_Number, Session_Date, Session_Type) VALUES (?, ?, ?, ?, ?)",
                            Statement.RETURN_GENERATED_KEYS
                        );

                        pst.setString(1, AttendanceCourseCode.getText());
                        pst.setInt(2, Integer.parseInt(AttendanceWeekNo.getText()));
                        pst.setInt(3, Integer.parseInt(AttendanceSessionNo.getText()));
                        pst.setString(4, AttendanceSessionDate.getText());
                        pst.setString(5, AttendanceSessionType.getText());

                        pst.executeUpdate();

                        ResultSet rs2 = pst.getGeneratedKeys();
                        if (rs2.next()) {
                            sessionId = rs2.getInt(1);
                        }
                    }

                    // 3. INSERT ATTENDANCE
                    PreparedStatement pst1 = con.prepareStatement(
                        "INSERT INTO attendance (ST_Id, Session_Id, Status) VALUES (?, ?, ?)"
                    );

                    pst1.setString(1, AttendanceStudentId.getText()); // student id
                    pst1.setInt(2, sessionId);
                    pst1.setString(3, AttendanceStatus.getText());

                    pst1.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Attendance Saved Successfully!");
                    AttendanceStudentId.setText("");
                    AttendanceStatus.setText("");
                    AttendanceSessionType.setText("");
                    AttendanceSessionDate.setText("");
                    AttendanceSessionNo.setText("");
                    AttendanceWeekNo.setText("");
                    AttendanceCourseCode.setText("");
             } catch (SQLException ex) {
                 System.getLogger(ToAddAttendance.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
         }
         
        // TODO add your handling code here:
    }//GEN-LAST:event_AttendanceAddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToAddAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttendanceAddButton;
    private javax.swing.JTextField AttendanceCourseCode;
    private javax.swing.JTextField AttendanceSessionDate;
    private javax.swing.JTextField AttendanceSessionNo;
    private javax.swing.JTextField AttendanceSessionType;
    private javax.swing.JTextField AttendanceStatus;
    private javax.swing.JTextField AttendanceStudentId;
    private javax.swing.JTextField AttendanceWeekNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
