/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codecrew;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author nipun
 */
public class ToAddAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToAddAttendance.class.getName());
    
    private final ToAttendanceService attendanceService = new ToAttendanceServiceDb();
    /**
     * Creates new form ToAddAttendance
     */
    public ToAddAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AttendanceStudentId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AttendanceWeekNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AttendanceSessionNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AttendanceSessionDate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AttendanceAddButton = new javax.swing.JButton();
        AttendanceCourseCode = new javax.swing.JComboBox<>();
        AttendanceSessionType = new javax.swing.JComboBox<>();
        AttendanceStatus = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("ADD ATTENDANCE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Student ID");

        AttendanceStudentId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceStudentId.setBorder(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Course Code");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Week No");

        AttendanceWeekNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceWeekNo.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Session No");

        AttendanceSessionNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceSessionNo.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Session Date");

        AttendanceSessionDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceSessionDate.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Session Type");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Status");

        AttendanceAddButton.setBackground(new java.awt.Color(255, 204, 0));
        AttendanceAddButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AttendanceAddButton.setForeground(new java.awt.Color(255, 255, 255));
        AttendanceAddButton.setText("ADD");
        AttendanceAddButton.addActionListener(this::AttendanceAddButtonActionPerformed);

        AttendanceCourseCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceCourseCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT1212", "ICT1222", "ICT1233", "ICT1242", "ICT1253", "ICT2122", "TCS1212", "TMS1213", "TMS1222", "TMS1231", "TMS1233", "TMS1242", "TMS1253", "TMS1261", "ENT1212", "ENG1222", "BST1272", "BST1262", "BST1253", "BST1242", "BST1232", "BST1222", "BST1212" }));
        AttendanceCourseCode.setBorder(null);

        AttendanceSessionType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceSessionType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theory", "Practical" }));
        AttendanceSessionType.setBorder(null);

        AttendanceStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AttendanceStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Present", "Absent", "Medical" }));
        AttendanceStatus.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AttendanceStudentId)
                            .addComponent(AttendanceCourseCode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AttendanceWeekNo)
                            .addComponent(AttendanceSessionNo)
                            .addComponent(AttendanceSessionDate)
                            .addComponent(AttendanceSessionType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AttendanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(430, 430, 430)
                        .addComponent(AttendanceAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceWeekNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceSessionNo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceSessionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceSessionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AttendanceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(AttendanceAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AttendanceAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceAddButtonActionPerformed

         if(AttendanceStudentId.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceStudentId.requestFocus();
         }
         /*else if(AttendanceCourseCod.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceCourseCod.requestFocus();
         }*/
         else if(AttendanceWeekNo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceWeekNo.requestFocus();
         }
         else if(AttendanceSessionNo.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceSessionNo.requestFocus();
         }
         else if(AttendanceSessionDate.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceSessionDate.requestFocus();
         }
         /*else if(AttendanceSessionTyp.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceSessionTyp.requestFocus();
         }
         else if(AttendanceStatu.getText().equals("")){
             JOptionPane.showMessageDialog(this, "please Fill all details.");
             AttendanceStatu.requestFocus();
         }*/
         else{
            /* 
             try {
                    Connection con = ToConnect.getConnection();
                    
                    PreparedStatement checkSession = con.prepareStatement(
                        "SELECT Session_Id FROM session WHERE Course_code=? AND Week_Number=? AND Session_Number=? AND Session_Date=? AND Session_Type=?"
                    );

                    checkSession.setString(1, AttendanceCourseCode.getSelectedItem().toString());
                    checkSession.setInt(2, Integer.parseInt(AttendanceWeekNo.getText()));
                    checkSession.setInt(3, Integer.parseInt(AttendanceSessionNo.getText()));
                    checkSession.setString(4, AttendanceSessionDate.getText());
                    checkSession.setString(5, AttendanceSessionType.getSelectedItem().toString());

                    ResultSet rs = checkSession.executeQuery();

                    int sessionId = 0;

                    if (rs.next()) {
                        // Session already exists
                        sessionId = rs.getInt("Session_Id");
                    } else {
                        // Insert new session
                        PreparedStatement pst = con.prepareStatement(
                            "INSERT INTO session (Course_code, Week_Number, Session_Number, Session_Date, Session_Type) VALUES (?, ?, ?, ?, ?)",
                            Statement.RETURN_GENERATED_KEYS
                        );

                        pst.setString(1, AttendanceCourseCode.getSelectedItem().toString());
                        pst.setInt(2, Integer.parseInt(AttendanceWeekNo.getText()));
                        pst.setInt(3, Integer.parseInt(AttendanceSessionNo.getText()));
                        pst.setString(4, AttendanceSessionDate.getText());
                        pst.setString(5, AttendanceSessionType.getSelectedItem().toString());

                        pst.executeUpdate();

                        ResultSet rs2 = pst.getGeneratedKeys();
                        if (rs2.next()) {
                            sessionId = rs2.getInt(1);
                        }
                    }

                    // 3. INSERT ATTENDANCE
                    PreparedStatement pst1 = con.prepareStatement(
                        "INSERT INTO toattendance (ST_Id, Session_Id, Status) VALUES (?, ?, ?)"
                    );

                    pst1.setString(1, AttendanceStudentId.getText()); // student id
                    pst1.setInt(2, sessionId);
                    pst1.setString(3, AttendanceStatus.getSelectedItem().toString());

                    pst1.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Attendance Saved Successfully!");
                    AttendanceStudentId.setText("");
                    AttendanceSessionDate.setText("");
                    AttendanceSessionNo.setText("");
                    AttendanceWeekNo.setText("");
                    
             } catch (SQLException ex) {
                 System.getLogger(ToAddAttendance.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
         }
         
        // TODO add your handling code here:
        
        */
            
            try {
    attendanceService.addAttendance(
        AttendanceStudentId.getText().trim(),
        AttendanceCourseCode.getSelectedItem().toString(),
        Integer.parseInt(AttendanceWeekNo.getText().trim()),
        Integer.parseInt(AttendanceSessionNo.getText().trim()),
        AttendanceSessionDate.getText().trim(),
        AttendanceSessionType.getSelectedItem().toString(),
        AttendanceStatus.getSelectedItem().toString()
    );

    JOptionPane.showMessageDialog(this, "Attendance Saved Successfully!");
    AttendanceStudentId.setText("");
    AttendanceSessionDate.setText("");
    AttendanceSessionNo.setText("");
    AttendanceWeekNo.setText("");

} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Week No and Session No must be numbers.");
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error saving attendance: " + ex.getMessage());
}
    }//GEN-LAST:event_AttendanceAddButtonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToAddAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AttendanceAddButton;
    private javax.swing.JComboBox<String> AttendanceCourseCode;
    private javax.swing.JTextField AttendanceSessionDate;
    private javax.swing.JTextField AttendanceSessionNo;
    private javax.swing.JComboBox<String> AttendanceSessionType;
    private javax.swing.JComboBox<String> AttendanceStatus;
    private javax.swing.JTextField AttendanceStudentId;
    private javax.swing.JTextField AttendanceWeekNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
