/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codecrew;

/**
 *
 * @author nipun
 */
public class ToHome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToHome.class.getName());

    /**
     * Creates new form ToHome
     */
    public ToHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noticeButton = new javax.swing.JButton();
        updateProfileButton = new javax.swing.JButton();
        attendanceButton = new javax.swing.JButton();
        medicalButton = new javax.swing.JButton();
        timeTablesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 760));

        noticeButton.setBackground(new java.awt.Color(255, 153, 0));
        noticeButton.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        noticeButton.setForeground(new java.awt.Color(255, 255, 255));
        noticeButton.setText("Notice");
        noticeButton.setBorder(null);
        noticeButton.addActionListener(this::noticeButtonActionPerformed);

        updateProfileButton.setBackground(new java.awt.Color(255, 153, 0));
        updateProfileButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        updateProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        updateProfileButton.setText("Update Profile");
        updateProfileButton.setBorder(null);
        updateProfileButton.addActionListener(this::updateProfileButtonActionPerformed);

        attendanceButton.setBackground(new java.awt.Color(255, 153, 0));
        attendanceButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        attendanceButton.setForeground(new java.awt.Color(255, 255, 255));
        attendanceButton.setText("Attendance");
        attendanceButton.setBorder(null);
        attendanceButton.addActionListener(this::attendanceButtonActionPerformed);

        medicalButton.setBackground(new java.awt.Color(255, 153, 0));
        medicalButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        medicalButton.setForeground(new java.awt.Color(255, 255, 255));
        medicalButton.setText("Medical");
        medicalButton.setBorder(null);
        medicalButton.addActionListener(this::medicalButtonActionPerformed);

        timeTablesButton.setBackground(new java.awt.Color(255, 153, 0));
        timeTablesButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        timeTablesButton.setForeground(new java.awt.Color(255, 255, 255));
        timeTablesButton.setText("Time Tables");
        timeTablesButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        timeTablesButton.addActionListener(this::timeTablesButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(685, 685, 685)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeTablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(noticeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(noticeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(updateProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(attendanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(medicalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(timeTablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeButtonActionPerformed
            
         new ToNotice().setVisible(true);  
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeButtonActionPerformed

    private void updateProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProfileButtonActionPerformed
            
            new ToUpdateProfile().setVisible(true);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_updateProfileButtonActionPerformed

    private void attendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceButtonActionPerformed

        new ToAttendance().setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_attendanceButtonActionPerformed

    private void medicalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicalButtonActionPerformed

              new ToMedical().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_medicalButtonActionPerformed

    private void timeTablesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTablesButtonActionPerformed

         new ToTimeTable().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTablesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToHome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendanceButton;
    private javax.swing.JButton medicalButton;
    private javax.swing.JButton noticeButton;
    private javax.swing.JButton timeTablesButton;
    private javax.swing.JButton updateProfileButton;
    // End of variables declaration//GEN-END:variables
}
