/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.codecrew;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author nipun
 */
public class ToRemoveMedical extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ToRemoveMedical.class.getName());

    /**
     * Creates new form ToRemoveMedical
     */
    public ToRemoveMedical() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        removeMedicalStudentId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        removeMedicalCourseCode = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        removeMedicalStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        removeMedicalRecordsShowTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        removeMedicalRemoveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("REMOVE MEDICAL");

        jLabel2.setText("Student ID");

        jLabel3.setText("Course Code");

        removeMedicalCourseCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT1212", "ICT1222", "ICT1233", "ICT1242", "ICT1253", "ICT2122", "TCS1212", "TMS1213", "TMS1222", "TMS1231", "TMS1233", "TMS1242", "TMS1253", "TMS1261", "ENT1212", "ENG1222", "BST1272", "BST1262", "BST1253", "BST1242", "BST1232", "BST1222", "BST1212" }));
        removeMedicalCourseCode.addActionListener(this::removeMedicalCourseCodeActionPerformed);

        jLabel4.setText("Status");

        removeMedicalStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Rejected" }));

        removeMedicalRecordsShowTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Student ", "Course ", "Date ", "Session ", "Type ", "Status ", "Reason "
            }
        ));
        jScrollPane1.setViewportView(removeMedicalRecordsShowTable);

        jButton1.setText("Search");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        removeMedicalRemoveButton.setText("Remove Medical");
        removeMedicalRemoveButton.addActionListener(this::removeMedicalRemoveButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeMedicalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeMedicalCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(removeMedicalStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(removeMedicalRemoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(removeMedicalStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(removeMedicalCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(removeMedicalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(removeMedicalRemoveButton)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeMedicalCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMedicalCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeMedicalCourseCodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        String studentId = removeMedicalStudentId.getText();
        String courseCode = removeMedicalCourseCode.getSelectedItem().toString();
        String status = removeMedicalStatus.getSelectedItem().toString();

        String sql = "SELECT m.Record_Id, m.ST_Id, m.Course_code, s.Session_Date, s.Session_Number, s.Session_Type, m.Status, m.Reason FROM medical_record m  JOIN session s ON m.Session_Id = s.Session_Id WHERE m.ST_Id LIKE ? AND m.Course_code LIKE ? AND m.Status LIKE ?";

        try (Connection con = ToConnect.getConnection();
             PreparedStatement pst = con.prepareStatement(sql)) {

            pst.setString(1, "%" + studentId + "%");
            pst.setString(2, "%" + courseCode + "%");
            pst.setString(3, "%" + status + "%");

            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) removeMedicalRecordsShowTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("Record_Id"),
                    rs.getString("ST_Id"),
                    rs.getString("Course_code"),
                    rs.getDate("Session_Date"),
                    rs.getInt("Session_Number"),
                    rs.getString("Session_Type"),
                    rs.getString("Status"),
                    rs.getString("Reason")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void removeMedicalRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMedicalRemoveButtonActionPerformed
       
        int row = removeMedicalRecordsShowTable.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select a record first!");
            return;
        }

        int recordId = (int) removeMedicalRecordsShowTable.getValueAt(row, 0);
        String studentId = removeMedicalRecordsShowTable.getValueAt(row, 1).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this medical record?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String getSessionSql = "SELECT Session_Id FROM medical_record WHERE Record_Id=?";
        String updateAttendanceSql = "UPDATE attendance SET Status='Absent' WHERE ST_Id=? AND Session_Id=?";
        String deleteSql = "DELETE FROM medical_record WHERE Record_Id=?";

        try (Connection con = ToConnect.getConnection()) {

            con.setAutoCommit(false); 

            int sessionId = 0;

            //  1. Get Session_Id
            try (PreparedStatement pst1 = con.prepareStatement(getSessionSql)) {
                pst1.setInt(1, recordId);
                ResultSet rs = pst1.executeQuery();

                if (rs.next()) {
                    sessionId = rs.getInt("Session_Id");
                }
            }

            //  2. Update attendance
            try (PreparedStatement pst2 = con.prepareStatement(updateAttendanceSql)) {
                pst2.setString(1, studentId);
                pst2.setInt(2, sessionId);
                pst2.executeUpdate();
            }

            //  3. Delete medical record
            try (PreparedStatement pst3 = con.prepareStatement(deleteSql)) {
                pst3.setInt(1, recordId);
                pst3.executeUpdate();
            }

            con.commit(); //  success

            JOptionPane.showMessageDialog(this, "Medical record removed & attendance updated!");

            searchMedical(); // refresh table

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_removeMedicalRemoveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ToRemoveMedical().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> removeMedicalCourseCode;
    private javax.swing.JTable removeMedicalRecordsShowTable;
    private javax.swing.JButton removeMedicalRemoveButton;
    private javax.swing.JComboBox<String> removeMedicalStatus;
    private javax.swing.JTextField removeMedicalStudentId;
    // End of variables declaration//GEN-END:variables

    private void searchMedical() {
            String studentId = removeMedicalStudentId.getText();
         String courseCode = removeMedicalCourseCode.getSelectedItem().toString();
         String status = removeMedicalStatus.getSelectedItem().toString();

         String sql = "SELECT m.Record_Id, m.ST_Id, m.Course_code, s.Session_Date, s.Session_Number, s.Session_Type, m.Status, m.Reason FROM medical_record m  JOIN session s ON m.Session_Id = s.Session_Id WHERE m.ST_Id LIKE ? AND m.Course_code LIKE ? AND m.Status LIKE ?";

         try (Connection con = ToConnect.getConnection();
              PreparedStatement pst = con.prepareStatement(sql)) {

             pst.setString(1, "%" + studentId + "%");
             pst.setString(2, "%" + courseCode + "%");
             pst.setString(3, "%" + status + "%");

             ResultSet rs = pst.executeQuery();

             DefaultTableModel model = (DefaultTableModel) removeMedicalRecordsShowTable.getModel();
             model.setRowCount(0);

             while (rs.next()) {
                 model.addRow(new Object[]{
                     rs.getInt("Record_Id"),
                     rs.getString("ST_Id"),
                     rs.getString("Course_code"),
                     rs.getDate("Session_Date"),
                     rs.getInt("Session_Number"),
                     rs.getString("Session_Type"),
                     rs.getString("Status"),
                     rs.getString("Reason")
                 });
             }

         } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e.getMessage());
         }

         }
}
